//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinjustInvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARMOrder
    {
        public System.Guid Id { get; set; }
        public int Num { get; set; }
        public string Name { get; set; }
        public string Segment { get; set; }
        public string IpAdress { get; set; }
        public string OperationSystem { get; set; }
        public string Memory { get; set; }
        public string InventNumber { get; set; }
        public string ComputerName { get; set; }
        public string Services { get; set; }
        public string AccountName { get; set; }

        public bool DBEquals(ARMOrder comp)
        {
            if (comp == null)
                return false;
            if (comp.InventNumber == this.InventNumber &&
                comp.IpAdress == this.IpAdress &&
                comp.Memory == this.Memory &&
                comp.Name == this.Name &&
                comp.Num == this.Num &&
                comp.OperationSystem == this.OperationSystem &&
                comp.Segment == this.Segment &&
                comp.Services == this.Services &&
                comp.AccountName == this.AccountName &&
                comp.ComputerName == this.ComputerName)
                return true;
            else
                return false;
        }
    }
}
