//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinjustInvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARMOrder
    {
        public System.Guid Id { get; set; }
        public int Num { get; set; }
        public string Name { get; set; }
        public string Segment { get; set; }
        public string IpAdress { get; set; }
        public string OperationSystem { get; set; }
        public string Memory { get; set; }
        public string InventNumber { get; set; }
        public string ComputerName { get; set; }
        public string Services { get; set; }
        public string AccountName { get; set; }
    }
}
