//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinjustInvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computers
    {
        public string Segment { get; set; }
        public int IP { get; set; }
        public string OperationSystem { get; set; }
        public int Memory { get; set; }
        public string InventNumber { get; set; }
        public string ComputerName { get; set; }
        public int Id { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
