//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinjustInvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.KartochkiOrder = new HashSet<KartochkiOrder>();
            this.TelephonyOrder = new HashSet<TelephonyOrder>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string IndexNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KartochkiOrder> KartochkiOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelephonyOrder> TelephonyOrder { get; set; }

        public bool DBEquals(Department comp)
        {
            if (comp == null)
                return false;
            if (comp.Name == this.Name &&
                comp.IndexNum == this.IndexNum)
                return true;
            else
                return false;
        }
    }
}
