//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinjustInvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class KartochkiOrder
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Card { get; set; }
        public string ReceivedSignature { get; set; }
        public string IssuedSignature { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
