//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinjustInvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrinterOrder
    {
        public System.Guid Id { get; set; }
        public Nullable<int> CabinetNum { get; set; }
        public string Name { get; set; }
        public string InventNumber { get; set; }
        public string Cartridge { get; set; }
        public string IP { get; set; }

        public bool DBEquals(PrinterOrder comp)
        {
            if (comp == null)
                return false;
            if (comp.CabinetNum == this.CabinetNum &&
                comp.Name == this.Name &&
                comp.InventNumber == this.InventNumber &&
                comp.Cartridge == this.Cartridge &&
                comp.IP == this.IP)
                return true;
            else
                return false;
        }
    }
}
