//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinjustInvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printers1
    {
        public int Id { get; set; }
        public string Office { get; set; }
        public string NamePrinter { get; set; }
        public string Cartridge { get; set; }
        public string InventNumber { get; set; }
        public Nullable<int> IP { get; set; }
    
        public virtual Departament Departament { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
