//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinjustInvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printers
    {
        public string Кабинет { get; set; }
        public string Модель_принтера { get; set; }
        public string Картридж { get; set; }
        public string Инвентарный_номер { get; set; }
        public string IP_адрес { get; set; }
    }
}
