//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinjustInvent
{
    using System;
    using System.Collections.Generic;
    
    public partial class USBOrder
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public string Size { get; set; }

        public bool DBEquals(USBOrder comp)
        {
            if (comp == null)
                return false;
            if (comp.Name == this.Name &&
                comp.SerialNumber == this.SerialNumber &&
                comp.Size == this.Size)
                return true;
            else
                return false;
        }
    }
}
